import {
  PAINTING_CONTENT,
  FLOORING_CONTENT,
  CABINETS_INSTALLATION_CONTENT,
  GENERAL_HOME_IMPROVEMENT_CONTENT,
  DOORS_INSTALLATION_CONTENT,
  CARPENTRY_FRAMING_CONTENT,
  CLOSETS_REMODEL_CONTENT,
  BATHROOM_REMODEL_CONTENT,
  KITCHEN_REMODEL_CONTENT,
  DRYWALL_WORK_CONTENT,
  TRIM_MOULDING_CONTENT,
} from "@/data/services/property-services";

export const SERVICES_PAGES = {
  "texture-painting": PAINTING_CONTENT,
  flooring: FLOORING_CONTENT,
  cabinets: CABINETS_INSTALLATION_CONTENT,
  general: GENERAL_HOME_IMPROVEMENT_CONTENT,
  carpentry: CARPENTRY_FRAMING_CONTENT,
  "doors-installation": DOORS_INSTALLATION_CONTENT,
  "closet-remodel": CLOSETS_REMODEL_CONTENT,
  "bathroom-remodel": BATHROOM_REMODEL_CONTENT,
  "kitchen-remodel": KITCHEN_REMODEL_CONTENT,
  "drywall-work": DRYWALL_WORK_CONTENT,
  "trim-moulding": TRIM_MOULDING_CONTENT,
};
